version: "3.9"
services:
  server:
    container_name: server
    build: ./server
    restart: "always"
    volumes:
      - ./server/app:/server/app
      - ./server/conf:/server/conf
    expose:
      - "5000"
    depends_on:
      - mongo
    networks:
      - backend
      - database

  trashcan:
    container_name: trashcan
    image: redis:6.2-alpine
    restart: always
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - ./trashcan/credentials.env
    networks:
      - database
    expose:
      - "6379"
    volumes:
      - trashcanvol:/data

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - server
    ports:
      - "443:443"
      - "80:80"
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo:4.2.23
    restart: always
    env_file:
      - ./mongo/credentials.env
    expose:
      - "27017"
    volumes:
      - mongovol:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - database

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    driver: bridge

volumes:
  mongovol:
    driver: local
    driver_opts:
      type: none
      device: '/participastorage'
      o: bind
  trashcanvol:
    driver: local
    driver_opts:
      type: none
      device: '/trashcanstorage'
      o: bind