openapi: 3.0.0
info:
  title: Participa
  version: 1.0.0
servers:
  - url: http://va
  - url: https://localhost
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: security
  - name: user
  - name: proposal
  - name: uploads
paths:
  /:
    get:
      tags:
        - security
      summary: Validate token
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /security/login:
    post:
      tags:
        - security
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: xabi@xabi.es
                password: changeme
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /security/logout:
    delete:
      tags:
        - security
      summary: Logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /security/refreshToken:
    get:
      tags:
        - security
      summary: Refresh
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/:
    get:
      tags:
        - user
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - user
      summary: edit
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - user
      summary: Delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /proposal/:
    post:
      tags:
        - proposal
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: >-
                  Hoy voy a contaros una historia maravillosa sobre la patata de
                  tu petete estamos en varias historias y etece errece bta chuty
                  skone jorobate flanders jorobate flanders jorobate flanders
                  jorobate flanders jorobate flanders jorobate flanders jorobate
                  flanders
                photos:
                  - 63d45318e09c5fef99779614
                  - 63d45338e09c5fef99779614
                title: Hi patato petete
                coordinates:
                  lat: 42.08687855718967
                  lng: -8.503621146082878
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /proposal/63bb24c1e3014ff43c340071:
    delete:
      tags:
        - proposal
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /proposal/63d459d162e83046a0b27c8a:
    put:
      tags:
        - proposal
      summary: edit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Super nuevo titulo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /uploads/photo:
    post:
      tags:
        - uploads
      summary: photo
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /uploads/photo/6450443ab13b889314d2cd50/13107662245843457970.jpg:
    get:
      tags:
        - uploads
      summary: presign
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}